import { Oracle11DDL } from '../oracle11/Oracle11DDL.js';

export class Oracle12DDL extends Oracle11DDL {
  _usesSequenceForAutoIncrement() { return false; }
  async createTableStructure(def) {
    const columns = []; const primaryKeys = [];
    for (const [attr, column] of Object.entries(def.columns)) {
      const name = column.field || attr; const parts = [this._q(name), this._adapter.mapDataType(column.type)];
      if (column.autoIncrement) parts.push('GENERATED BY DEFAULT AS IDENTITY');
      if (column.defaultValue !== undefined && column.defaultValue !== null && typeof column.defaultValue !== 'function') parts.push(`DEFAULT ${this._formatDefaultValue(column.defaultValue)}`);
      if (!column.allowNull && !column.primaryKey) parts.push('NOT NULL');
      columns.push(parts.join(' ')); if (column.primaryKey) primaryKeys.push(name);
    }
    if (primaryKeys.length) columns.push(`PRIMARY KEY (${primaryKeys.map(key => this._q(key)).join(', ')})`);
    await this._execute(`CREATE TABLE ${this._q(def.tableName)} (\n  ${columns.join(',\n  ')}\n)`);
  }
}
